<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">  
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="http://localhost/web2/TPE-web2">
    <link rel="stylesheet" href="./TPE-web2/css/style.css">
    <title>Home</title>
</head>

<body>
    <header>
        <nav>
            <div class="logo">
                <a href="TPE-web2/home"><img src="./TPE-web2/imagenes/img_logo.png" class="imglogo" alt="PAGINA INICIO"></a>
            </div>
            <div class="btn-menu"><a>menú</a></div>

                <ul class="navbar">
                    <li><a href="TPE-web2/home">INICIO</a></li>
                    <li><a href="TPE-web2/tienda">TIENDA</a></li>
                    <?php

                    if (isset($_SESSION['USER_ID'])) {
                        // Si la variable de sesión USER_ID existe, muestra el enlace de logout
                        echo '<li><a href="TPE-web2/logout">LOGOUT</a></li>';
                    } 
                    ?>
                </ul>
            </div>
        </nav>
    </header>
</body>