<?php require './templates/header.phtml'?>

<div class="login">
    <form method="POST" action="TPE-web2/auth">
        <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre">
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="password" required id="password" name="password">
        </div>

        <?php if ($error) : ?>
            <div role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
       
        <button type="submit">Entrar</button>
    </form>
</div>

<?php require './templates/footer.phtml'?>
